### PR TITLE
Feature map legend tooltip

### PR DESCRIPTION
**Pull request by mitchthorson**
### What's in this pull request

- [x] New component/feature

### Description

This pull request combines several new, intertwined feature branches into a single place. This includes:
- an `<SVGMap>` component
-  several associated layer components (`SVGPolygonLayer`, `SVGPointLayer`, `SVGLabelLayer`)
- A related `ColorLegend` component
- A `Tooltip` component

### Before submitting, please check that you've

- [x] Formatted your code correctly (i.e., prettier cleaned it up)
- [x] Documented any new components or features
- [x] Added any changes in this PR to the `CHANGELOG.md` `Next` section
- [x] If this pull request includes a new component or feature, has it been exported from one of the library's entry points?

### CODE REVIEW

**Comment by benkates** [comment]
A few thoughts after taking this for a spin a bit closer:

- Should `null` be allowed as a value for props like `fill` and `stroke` in the svg layers? Right now it needs to be a function to render.
    - Related: Should we auto-convert `null` to "none" as the designated value? Right now the user needs to know to add "none" as a string.
- I'm not getting tooltip collision detection in the "Loading topojson, custom projections, custom color scales" story for `SVGMap`

**Comment by benkates** [comment]
A few thoughts after taking this for a spin a bit closer:

- Should `null` be allowed as a value for props like `fill` and `stroke` in the svg layers? Right now it needs to be a function to render.
    - Related: Should we auto-convert `null` to "none" as the designated value? Right now the user needs to know to add "none" as a string.
- I'm not getting tooltip collision detection in the "Loading topojson, custom projections, custom color scales" story for `SVGMap`

**Comment by benkates** [comment]
test comment

**Comment by mitchthorson** [comment]
@benkates I'm kinda torn about the question about supporting `null` for `fill` and `stroke`. My thinking on enforcing it as a string is that `"none"` is a [valid property for SVG fills](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes) and `null` isn't. So forcing the user of the component to pass a string that is valid SVG code or a funciton that returns a valid string just seems simpler to me than guessing about what `null` means (no fill? transparent fill?). I'm not totally opposed to doing a check for `null` and converting it to `none`, but I feel like it may make the most sense to say: Just pass something here that complies with the SVG standard.

**Review by benkates — APPROVED** [review]

**Pull request merged**
