### PR TITLE
Add wide Urban logo

### PR DESCRIPTION
**Pull request by benkates**
### What's in this pull request

- [x] New component/feature

### Description

Add wide Urban logo

### Before submitting, please check that you've

- [x] Formatted your code correctly (i.e., prettier cleaned it up)
- [x] Documented any new components or features
- [x] Added any changes in this PR to the `CHANGELOG.md` `Next` section
- [x] If this pull request includes a new component or feature, has it been exported from one of the library's entry points?

### CODE REVIEW

**Review by benkates — COMMENTED** [review]
@mitchthorson unable to get the entire logo to show for some reason, would love your eyes.

**Review by benkates — COMMENTED** [review]
Also, maybe we create a "Logos" storybook nav section?

**Review by mitchthorson — CHANGES_REQUESTED** [review]
Looks like all of the `<path>` elements for the word "INSTITUTE" don't have any fill. You may also need an extra color variable that is black for the `color` variant and white for the `white` variant

**Comment by benkates** [comment]
@mitchthorson Thank you! Implemented the fill as well as the "Logos" story folder, feel free to change its placement

**Review by mitchthorson — APPROVED** [review]

**Pull request merged**
